language: node_js
node_js:
  - 12

script:
  - npm run lint
  - npm run test:ci

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run build
      deploy:
        provider: script
        skip_cleanup: true
        on:
          branch: master
        script:
          - npm run release

      after_success: npm run coverage