language: node_js
node_js:
  - 8
  - 10

script:
  - npm run lint
  - npm test
  - npm run build

deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
  script:
    - npm run release

after_success: npm run coverage